/**
 * Symbol branding colors
 */
const COLORS = {
	PRIMARY: '#5200c6',
	SECONDARY:'#44004e',
	PINK: '#ff00ff',
	BLUE: '#00c8ff',
	GREEN: '#33dd50',
	ORANGE: '#ff9600',
	BLACK: '#000000',
	GREY1:'#333333',
	GREY2:'#666666',
	GREY3:'#999999',
	GREY4:'#cccccc',
	GREY5:'#f2f2f2',
	WHITE: '#ffffff'
};

export default {
	color: {
		// Brand colors
		...COLORS,

		// On Light Background
		onLight: {
			TITLE: 				COLORS.PINK,
			BUTTON_BACK: 		COLORS.BLACK,
			BUTTON_CLOSE:		COLORS.BLACK,

			TEXT: 				COLORS.SECONDARY,

			BUTTON: 			COLORS.PRIMARY,
			BUTTON_DISABLED: 	COLORS.PRIMARY,
			BUTTON_TEXT: 		COLORS.WHITE,
			BUTTON_TEXT_DISABLED: COLORS.WHITE,
			CONTROL: 			COLORS.PRIMARY,
			CONTROL_ACTIVE: 	COLORS.PRIMARY,
			CONTROL_DISABLED: 	COLORS.PRIMARY,
			CONTROL_TEXT: 		COLORS.WHITE,
			CONTROL_TEXT_ACTIVE: COLORS.WHITE,
			CONTROL_TEXT_DISABLED: COLORS.WHITE,
		},

		// On Dark Background
		onDark: {
			TITLE: 				COLORS.WHITE,
			BUTTON_BACK: 		COLORS.WHITE,
			BUTTON_CLOSE:		COLORS.WHITE,

			TEXT: 				COLORS.WHITE,

			BUTTON: 			COLORS.PINK,
			BUTTON_DISABLED: 	COLORS.PRIMARY,
			BUTTON_TEXT: 		COLORS.WHITE,
			BUTTON_TEXT_DISABLED: COLORS.WHITE,
			CONTROL: 			COLORS.PRIMARY,
			CONTROL_ACTIVE: 	COLORS.PRIMARY,
			CONTROL_DISABLED: 	COLORS.PRIMARY,
			CONTROL_TEXT: 		COLORS.WHITE,
			CONTROL_TEXT_ACTIVE: COLORS.WHITE,
			CONTROL_TEXT_DISABLED: COLORS.WHITE,
		},
	},

	fontSize: {
		PAGE_TITLE: '',
		PAGE_SUBTITLE: '',
		PAGE_TEXT: '',
		MODAL_TITLE: '',
	}
};
