# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def ensure_temp_keychain(name, password)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
  create_keychain(
    name: name,
    password: password,
    unlock: true,
    timeout: false
  )
end
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    increment_build_number(
        build_number: ENV["BUILD_NUMBER"],
        xcodeproj: "SymbolWallet.xcodeproj"
    )
    increment_version_number(
      version_number: ENV["VERSION_NUMBER"],
      xcodeproj: "SymbolWallet.xcodeproj"
    )
    ensure_temp_keychain(ENV["FASTLANE_KEYCHAIN"], ENV["FASTLANE_KEYCHAIN_PASSWORD"])
    setup_jenkins(force: true, keychain_path: ENV["FASTLANE_KEYCHAIN"], keychain_password: ENV["FASTLANE_KEYCHAIN_PASSWORD"], add_keychain_to_search_list: true)
    #, set_default_keychain: true
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
      key_content: ENV['APP_STORE_CONNECT_API_KEY_KEY'],
      is_key_content_base64: true
    )
    match(type: "appstore")
    build_app(workspace: "SymbolWallet.xcworkspace", scheme: "Symbol")
    upload_to_testflight
  end
end