# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    increment_build_number(
        build_number: ENV["BUILD_NUMBER"],
        xcodeproj: "SymbolWallet.xcodeproj"
    )
    increment_version_number(
      version_number: ENV["VERSION_NUMBER"],
      xcodeproj: "SymbolWallet.xcodeproj"
    )
    match(type: "appstore")
    build_app(workspace: "SymbolWallet.xcworkspace", scheme: "Symbol")
    upload_to_testflight
  end
end
